name: Docker Image CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Alibaba Cloud Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY_SERVER }}
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.ALIYUN_REGISTRY_SERVER }}/com-seaurl/seaurl-drawio:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.ALIYUN_REGISTRY_SERVER }}/com-seaurl/seaurl-drawio:latest

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: '1.24.6' # Specify the kubectl version you need

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace drawio
          kubectl apply -f k8s-deploy.yaml -n drawio
#          kubectl rollout status deployment/seaurl-drawio-deployment